using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Pattern.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Permissions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Permissions", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Provinces",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Plaka = table.Column<int>(type: "integer", nullable: false),
                    ProvinceText = table.Column<string>(type: "text", nullable: false),
                    AreaCode = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Provinces", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Roles",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CreationTime = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatorUserId = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModificationTime = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifierUserId = table.Column<Guid>(type: "uuid", nullable: true),
                    DeletionTime = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    DeleterUserId = table.Column<Guid>(type: "uuid", nullable: true),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    Name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    NormalizedName = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Roles", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    FirstName = table.Column<string>(type: "text", nullable: false),
                    LastName = table.Column<string>(type: "text", nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    CreationTime = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatorUserId = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModificationTime = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifierUserId = table.Column<Guid>(type: "uuid", nullable: true),
                    DeletionTime = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    DeleterUserId = table.Column<Guid>(type: "uuid", nullable: true),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    UserName = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    NormalizedUserName = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    Email = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    NormalizedEmail = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    EmailConfirmed = table.Column<bool>(type: "boolean", nullable: false),
                    PasswordHash = table.Column<string>(type: "text", nullable: true),
                    SecurityStamp = table.Column<string>(type: "text", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "text", nullable: true),
                    PhoneNumber = table.Column<string>(type: "text", nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(type: "boolean", nullable: false),
                    TwoFactorEnabled = table.Column<bool>(type: "boolean", nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LockoutEnabled = table.Column<bool>(type: "boolean", nullable: false),
                    AccessFailedCount = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Districts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    DistrictText = table.Column<string>(type: "text", nullable: false),
                    ProvinceId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Districts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Districts_Provinces_ProvinceId",
                        column: x => x.ProvinceId,
                        principalTable: "Provinces",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "RoleClaims",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    RoleId = table.Column<Guid>(type: "uuid", nullable: false),
                    ClaimType = table.Column<string>(type: "text", nullable: true),
                    ClaimValue = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RoleClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RoleClaims_Roles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "RolePermissions",
                columns: table => new
                {
                    RoleId = table.Column<Guid>(type: "uuid", nullable: false),
                    PermissionId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RolePermissions", x => new { x.RoleId, x.PermissionId });
                    table.ForeignKey(
                        name: "FK_RolePermissions_Permissions_PermissionId",
                        column: x => x.PermissionId,
                        principalTable: "Permissions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_RolePermissions_Roles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserClaims",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    ClaimType = table.Column<string>(type: "text", nullable: true),
                    ClaimValue = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserClaims_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserLogins",
                columns: table => new
                {
                    LoginProvider = table.Column<string>(type: "text", nullable: false),
                    ProviderKey = table.Column<string>(type: "text", nullable: false),
                    ProviderDisplayName = table.Column<string>(type: "text", nullable: true),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserLogins", x => new { x.LoginProvider, x.ProviderKey });
                    table.ForeignKey(
                        name: "FK_UserLogins_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserRefreshTokens",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Code = table.Column<string>(type: "text", nullable: false),
                    Expiration = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserRefreshTokens", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserRefreshTokens_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserRoles",
                columns: table => new
                {
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    RoleId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserRoles", x => new { x.UserId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_UserRoles_Roles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_UserRoles_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserTokens",
                columns: table => new
                {
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    LoginProvider = table.Column<string>(type: "text", nullable: false),
                    Name = table.Column<string>(type: "text", nullable: false),
                    Value = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
                    table.ForeignKey(
                        name: "FK_UserTokens_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Permissions",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "UserDefault" },
                    { 2, "UserCreate" },
                    { 3, "UserUpdate" },
                    { 4, "UserDelete" },
                    { 5, "AccountDefault" },
                    { 6, "AccountUpdate" },
                    { 7, "AccountDelete" },
                    { 8, "EmailChange" },
                    { 9, "ChangePassword" },
                    { 10, "RoleDefault" },
                    { 11, "RoleCreate" },
                    { 12, "RoleUpdate" },
                    { 13, "RoleDelete" }
                });

            migrationBuilder.InsertData(
                table: "Provinces",
                columns: new[] { "Id", "AreaCode", "Plaka", "ProvinceText" },
                values: new object[,]
                {
                    { 1, "380", 81, "DÜZCE" },
                    { 2, "328", 80, "OSMANİYE" },
                    { 3, "348", 79, "KİLİS" },
                    { 4, "370", 78, "KARABÜK" },
                    { 5, "226", 77, "YALOVA" },
                    { 6, "476", 76, "IĞDIR" },
                    { 7, "478", 75, "ARDAHAN" },
                    { 8, "378", 74, "BARTIN" },
                    { 9, "486", 73, "ŞIRNAK" },
                    { 10, "488", 72, "BATMAN" },
                    { 11, "318", 71, "KIRIKKALE" },
                    { 12, "338", 70, "KARAMAN" },
                    { 13, "458", 69, "BAYBURT" },
                    { 14, "382", 68, "AKSARAY" },
                    { 15, "372", 67, "ZONGULDAK" },
                    { 16, "354", 66, "YOZGAT" },
                    { 17, "432", 65, "VAN" },
                    { 18, "276", 64, "UŞAK" },
                    { 19, "414", 63, "ŞANLIURFA" },
                    { 20, "428", 62, "TUNCELİ" },
                    { 21, "462", 61, "TRABZON" },
                    { 22, "356", 60, "TOKAT" },
                    { 23, "282", 59, "TEKİRDAĞ" },
                    { 24, "346", 58, "SİVAS" },
                    { 25, "368", 57, "SİNOP" },
                    { 26, "484", 56, "SİİRT" },
                    { 27, "362", 55, "SAMSUN" },
                    { 28, "264", 54, "SAKARYA" },
                    { 29, "464", 53, "RİZE" },
                    { 30, "452", 52, "ORDU" },
                    { 31, "388", 51, "NİĞDE" },
                    { 32, "384", 50, "NEVŞEHİR" },
                    { 33, "436", 49, "MUŞ" },
                    { 34, "252", 48, "MUĞLA" },
                    { 35, "482", 47, "MARDİN" },
                    { 36, "344", 46, "KAHRAMANMARAŞ" },
                    { 37, "236", 45, "MANİSA" },
                    { 38, "422", 44, "MALATYA" },
                    { 39, "274", 43, "KÜTAHYA" },
                    { 40, "332", 42, "KONYA" },
                    { 41, "262", 41, "KOCAELİ" },
                    { 42, "386", 40, "KIRŞEHİR" },
                    { 43, "288", 39, "KIRKLARELİ" },
                    { 44, "352", 38, "KAYSERİ" },
                    { 45, "366", 37, "KASTAMONU" },
                    { 46, "474", 36, "KARS" },
                    { 47, "232", 35, "İZMİR" },
                    { 48, "212", 34, "İSTANBUL" },
                    { 49, "324", 33, "MERSİN" },
                    { 50, "246", 32, "ISPARTA" },
                    { 51, "326", 31, "HATAY" },
                    { 52, "438", 30, "HAKKARİ" },
                    { 53, "456", 29, "GÜMÜŞHANE" },
                    { 54, "454", 28, "GİRESUN" },
                    { 55, "342", 27, "GAZİANTEP" },
                    { 56, "222", 26, "ESKİŞEHİR" },
                    { 57, "442", 25, "ERZURUM" },
                    { 58, "446", 24, "ERZİNCAN" },
                    { 59, "424", 23, "ELAZIĞ" },
                    { 60, "284", 22, "EDİRNE" },
                    { 61, "412", 21, "DİYARBAKIR" },
                    { 62, "258", 20, "DENİZLİ" },
                    { 63, "364", 19, "ÇORUM" },
                    { 64, "376", 18, "ÇANKIRI" },
                    { 65, "286", 17, "ÇANAKKALE" },
                    { 66, "224", 16, "BURSA" },
                    { 67, "248", 15, "BURDUR" },
                    { 68, "374", 14, "BOLU" },
                    { 69, "434", 13, "BİTLİS" },
                    { 70, "426", 12, "BİNGÖL" },
                    { 71, "228", 11, "BİLECİK" },
                    { 72, "266", 10, "BALIKESİR" },
                    { 73, "256", 9, "AYDIN" },
                    { 74, "466", 8, "ARTVİN" },
                    { 75, "242", 7, "ANTALYA" },
                    { 76, "312", 6, "ANKARA" },
                    { 77, "358", 5, "AMASYA" },
                    { 78, "472", 4, "AĞRI" },
                    { 79, "272", 3, "AFYONKARAHİSAR" },
                    { 80, "416", 2, "ADIYAMAN" },
                    { 81, "322", 1, "ADANA" }
                });

            migrationBuilder.InsertData(
                table: "Roles",
                columns: new[] { "Id", "ConcurrencyStamp", "CreationTime", "CreatorUserId", "DeleterUserId", "DeletionTime", "IsDeleted", "LastModificationTime", "LastModifierUserId", "Name", "NormalizedName" },
                values: new object[] { new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5"), "0043caf9-939f-431b-8c7c-885a451c41e2", new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), null, null, null, false, null, null, "Admin", "ADMIN" });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "AccessFailedCount", "ConcurrencyStamp", "CreationTime", "CreatorUserId", "DeleterUserId", "DeletionTime", "Email", "EmailConfirmed", "FirstName", "IsActive", "IsDeleted", "LastModificationTime", "LastModifierUserId", "LastName", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled", "UserName" },
                values: new object[] { new Guid("b8c4f733-8811-47dc-83f1-6a88d3edf782"), 0, "c2e96e54-6a11-4aba-a899-67160fbebdae", new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), null, null, null, "admin@admin.com", true, "Admin", true, false, null, null, "Admin", false, null, "ADMIN@ADMIN.COM", "ADMIN", "AQAAAAIAAYagAAAAEKbcPpIrFuX+G69GogAX6Caisc0GGujyFAuV6mkOF1adKoRHHmT0R94NHsq1MW/fXA==", null, false, "9b92a510-afcb-452e-93d6-bc817f9fe2e3", false, "admin" });

            migrationBuilder.InsertData(
                table: "Districts",
                columns: new[] { "Id", "DistrictText", "ProvinceId" },
                values: new object[,]
                {
                    { 1, "AKÇAKOCA", 1 },
                    { 2, "CUMAYERİ", 1 },
                    { 3, "ÇİLİMLİ", 1 },
                    { 4, "MERKEZ", 1 },
                    { 5, "GÖLYAKA", 1 },
                    { 6, "GÜMÜŞOVA", 1 },
                    { 7, "KAYNAŞLI", 1 },
                    { 8, "YIĞILCA", 1 },
                    { 9, "BAHÇE", 2 },
                    { 10, "DÜZİÇİ", 2 },
                    { 11, "HASANBEYLİ", 2 },
                    { 12, "KADİRLİ", 2 },
                    { 13, "MERKEZ", 2 },
                    { 14, "SUMBAS", 2 },
                    { 15, "TOPRAKKALE", 2 },
                    { 16, "ELBEYLİ", 3 },
                    { 17, "MERKEZ", 3 },
                    { 18, "MUSABEYLİ", 3 },
                    { 19, "POLATELİ", 3 },
                    { 20, "EFLANİ", 4 },
                    { 21, "ESKİPAZAR", 4 },
                    { 22, "MERKEZ", 4 },
                    { 23, "OVACIK", 4 },
                    { 24, "SAFRANBOLU", 4 },
                    { 25, "YENİCE", 4 },
                    { 26, "ALTINOVA", 5 },
                    { 27, "ARMUTLU", 5 },
                    { 28, "ÇINARCIK", 5 },
                    { 29, "ÇİFTLİKKÖY", 5 },
                    { 30, "TERMAL", 5 },
                    { 31, "MERKEZ", 5 },
                    { 32, "ARALIK", 6 },
                    { 33, "MERKEZ", 6 },
                    { 34, "KARAKOYUNLU", 6 },
                    { 35, "TUZLUCA", 6 },
                    { 36, "MERKEZ", 7 },
                    { 37, "ÇILDIR", 7 },
                    { 38, "DAMAL", 7 },
                    { 39, "GÖLE", 7 },
                    { 40, "HANAK", 7 },
                    { 41, "POSOF", 7 },
                    { 42, "AMASRA", 8 },
                    { 43, "MERKEZ", 8 },
                    { 44, "KURUCAŞİLE", 8 },
                    { 45, "ULUS", 8 },
                    { 46, "BEYTÜŞŞEBAP", 9 },
                    { 47, "CİZRE", 9 },
                    { 48, "GÜÇLÜKONAK", 9 },
                    { 49, "İDİL", 9 },
                    { 50, "SİLOPİ", 9 },
                    { 51, "MERKEZ", 9 },
                    { 52, "ULUDERE", 9 },
                    { 53, "MERKEZ", 10 },
                    { 54, "BEŞİRİ", 10 },
                    { 55, "GERCÜŞ", 10 },
                    { 56, "HASANKEYF", 10 },
                    { 57, "KOZLUK", 10 },
                    { 58, "SASON", 10 },
                    { 59, "BAHŞİLİ", 11 },
                    { 60, "BALIŞEYH", 11 },
                    { 61, "ÇELEBİ", 11 },
                    { 62, "DELİCE", 11 },
                    { 63, "KARAKEÇİLİ", 11 },
                    { 64, "KESKİN", 11 },
                    { 65, "MERKEZ", 11 },
                    { 66, "SULAKYURT", 11 },
                    { 67, "YAHŞİHAN", 11 },
                    { 68, "AYRANCI", 12 },
                    { 69, "BAŞYAYLA", 12 },
                    { 70, "ERMENEK", 12 },
                    { 71, "MERKEZ", 12 },
                    { 72, "KAZIMKARABEKİR", 12 },
                    { 73, "SARIVELİLER", 12 },
                    { 74, "AYDINTEPE", 13 },
                    { 75, "MERKEZ", 13 },
                    { 76, "DEMİRÖZÜ", 13 },
                    { 77, "AĞAÇÖREN", 14 },
                    { 78, "MERKEZ", 14 },
                    { 79, "ESKİL", 14 },
                    { 80, "GÜLAĞAÇ", 14 },
                    { 81, "GÜZELYURT", 14 },
                    { 82, "ORTAKÖY", 14 },
                    { 83, "SARIYAHŞİ", 14 },
                    { 84, "ALAPLI", 15 },
                    { 85, "ÇAYCUMA", 15 },
                    { 86, "DEVREK", 15 },
                    { 87, "GÖKÇEBEY", 15 },
                    { 88, "EREĞLİ", 15 },
                    { 89, "MERKEZ", 15 },
                    { 90, "AKDAĞMADENİ", 16 },
                    { 91, "AYDINCIK", 16 },
                    { 92, "BOĞAZLIYAN", 16 },
                    { 93, "ÇANDIR", 16 },
                    { 94, "ÇAYIRALAN", 16 },
                    { 95, "ÇEKEREK", 16 },
                    { 96, "KADIŞEHRİ", 16 },
                    { 97, "SARAYKENT", 16 },
                    { 98, "SARIKAYA", 16 },
                    { 99, "SORGUN", 16 },
                    { 100, "ŞEFAATLİ", 16 },
                    { 101, "YENİFAKILI", 16 },
                    { 102, "YERKÖY", 16 },
                    { 103, "MERKEZ", 16 },
                    { 104, "BAHÇESARAY", 17 },
                    { 105, "BAŞKALE", 17 },
                    { 106, "ÇALDIRAN", 17 },
                    { 107, "ÇATAK", 17 },
                    { 108, "EDREMİT", 17 },
                    { 109, "ERCİŞ", 17 },
                    { 110, "GEVAŞ", 17 },
                    { 111, "GÜRPINAR", 17 },
                    { 112, "MURADİYE", 17 },
                    { 113, "ÖZALP", 17 },
                    { 114, "SARAY", 17 },
                    { 115, "MERKEZ", 17 },
                    { 116, "BANAZ", 18 },
                    { 117, "EŞME", 18 },
                    { 118, "KARAHALLI", 18 },
                    { 119, "SİVASLI", 18 },
                    { 120, "ULUBEY", 18 },
                    { 121, "MERKEZ", 18 },
                    { 122, "AKÇAKALE", 19 },
                    { 123, "BİRECİK", 19 },
                    { 124, "BOZOVA", 19 },
                    { 125, "CEYLANPINAR", 19 },
                    { 126, "HALFETİ", 19 },
                    { 127, "HARRAN", 19 },
                    { 128, "HİLVAN", 19 },
                    { 129, "SİVEREK", 19 },
                    { 130, "SURUÇ", 19 },
                    { 131, "MERKEZ", 19 },
                    { 132, "VİRANŞEHİR", 19 },
                    { 133, "ÇEMİŞGEZEK", 20 },
                    { 134, "HOZAT", 20 },
                    { 135, "MAZGİRT", 20 },
                    { 136, "NAZIMİYE", 20 },
                    { 137, "OVACIK", 20 },
                    { 138, "PERTEK", 20 },
                    { 139, "PÜLÜMÜR", 20 },
                    { 140, "MERKEZ", 20 },
                    { 141, "AKÇAABAT", 21 },
                    { 142, "ARAKLI", 21 },
                    { 143, "ARSİN", 21 },
                    { 144, "BEŞİKDÜZÜ", 21 },
                    { 145, "ÇARŞIBAŞI", 21 },
                    { 146, "ÇAYKARA", 21 },
                    { 147, "DERNEKPAZARI", 21 },
                    { 148, "DÜZKÖY", 21 },
                    { 149, "HAYRAT", 21 },
                    { 150, "KÖPRÜBAŞI", 21 },
                    { 151, "MAÇKA", 21 },
                    { 152, "OF", 21 },
                    { 153, "SÜRMENE", 21 },
                    { 154, "ŞALPAZARI", 21 },
                    { 155, "TONYA", 21 },
                    { 156, "MERKEZ", 21 },
                    { 157, "VAKFIKEBİR", 21 },
                    { 158, "YOMRA", 21 },
                    { 159, "ALMUS", 22 },
                    { 160, "ARTOVA", 22 },
                    { 161, "BAŞÇİFTLİK", 22 },
                    { 162, "ERBAA", 22 },
                    { 163, "NİKSAR", 22 },
                    { 164, "PAZAR", 22 },
                    { 165, "REŞADİYE", 22 },
                    { 166, "SULUSARAY", 22 },
                    { 167, "MERKEZ", 22 },
                    { 168, "TURHAL", 22 },
                    { 169, "YEŞİLYURT", 22 },
                    { 170, "ZİLE", 22 },
                    { 171, "ÇERKEZKÖY", 23 },
                    { 172, "ÇORLU", 23 },
                    { 173, "HAYRABOLU", 23 },
                    { 174, "MALKARA", 23 },
                    { 175, "MARMARAEREĞLİSİ", 23 },
                    { 176, "MURATLI", 23 },
                    { 177, "SARAY", 23 },
                    { 178, "ŞARKÖY", 23 },
                    { 179, "MERKEZ", 23 },
                    { 180, "AKINCILAR", 24 },
                    { 181, "ALTINYAYLA", 24 },
                    { 182, "DİVRİĞİ", 24 },
                    { 183, "DOĞANŞAR", 24 },
                    { 184, "GEMEREK", 24 },
                    { 185, "GÖLOVA", 24 },
                    { 186, "GÜRÜN", 24 },
                    { 187, "HAFİK", 24 },
                    { 188, "İMRANLI", 24 },
                    { 189, "KANGAL", 24 },
                    { 190, "KOYULHİSAR", 24 },
                    { 191, "MERKEZ", 24 },
                    { 192, "SUŞEHRİ", 24 },
                    { 193, "ŞARKIŞLA", 24 },
                    { 194, "ULAŞ", 24 },
                    { 195, "YILDIZELİ", 24 },
                    { 196, "ZARA", 24 },
                    { 197, "AYANCIK", 25 },
                    { 198, "BOYABAT", 25 },
                    { 199, "DİKMEN", 25 },
                    { 200, "DURAĞAN", 25 },
                    { 201, "ERFELEK", 25 },
                    { 202, "GERZE", 25 },
                    { 203, "SARAYDÜZÜ", 25 },
                    { 204, "MERKEZ", 25 },
                    { 205, "TÜRKELİ", 25 },
                    { 207, "BAYKAN", 26 },
                    { 208, "ERUH", 26 },
                    { 209, "KURTALAN", 26 },
                    { 210, "PERVARİ", 26 },
                    { 211, "MERKEZ", 26 },
                    { 212, "ŞİRVAN", 26 },
                    { 213, "ALAÇAM", 27 },
                    { 214, "ASARCIK", 27 },
                    { 215, "ATAKUM", 27 },
                    { 216, "AYVACIK", 27 },
                    { 217, "BAFRA", 27 },
                    { 218, "CANİK", 27 },
                    { 219, "ÇARŞAMBA", 27 },
                    { 220, "HAVZA", 27 },
                    { 221, "İLKADIM", 27 },
                    { 222, "KAVAK", 27 },
                    { 223, "LADİK", 27 },
                    { 225, "SALIPAZARI", 27 },
                    { 226, "TEKKEKÖY", 27 },
                    { 227, "TERME", 27 },
                    { 228, "VEZİRKÖPRÜ", 27 },
                    { 229, "YAKAKENT", 27 },
                    { 230, "ADAPAZARI", 28 },
                    { 231, "AKYAZI", 28 },
                    { 232, "ARİFİYE", 28 },
                    { 233, "ERENLER", 28 },
                    { 234, "FERİZLİ", 28 },
                    { 235, "GEYVE", 28 },
                    { 236, "HENDEK", 28 },
                    { 237, "KARAPÜRÇEK", 28 },
                    { 238, "KARASU", 28 },
                    { 239, "KAYNARCA", 28 },
                    { 240, "KOCAALİ", 28 },
                    { 241, "PAMUKOVA", 28 },
                    { 242, "SAPANCA", 28 },
                    { 243, "SERDİVAN", 28 },
                    { 244, "SÖĞÜTLÜ", 28 },
                    { 245, "TARAKLI", 28 },
                    { 246, "ARDEŞEN", 29 },
                    { 247, "ÇAMLIHEMŞİN", 29 },
                    { 248, "ÇAYELİ", 29 },
                    { 249, "DEREPAZARI", 29 },
                    { 250, "FINDIKLI", 29 },
                    { 251, "GÜNEYSU", 29 },
                    { 252, "HEMŞİN", 29 },
                    { 253, "İKİZDERE", 29 },
                    { 254, "İYİDERE", 29 },
                    { 255, "KALKANDERE", 29 },
                    { 256, "PAZAR", 29 },
                    { 257, "MERKEZ", 29 },
                    { 258, "AKKUŞ", 30 },
                    { 259, "AYBASTI", 30 },
                    { 260, "ÇAMAŞ", 30 },
                    { 261, "ÇATALPINAR", 30 },
                    { 262, "ÇAYBAŞI", 30 },
                    { 263, "FATSA", 30 },
                    { 264, "GÖLKÖY", 30 },
                    { 265, "GÜLYALI", 30 },
                    { 266, "GÜRGENTEPE", 30 },
                    { 267, "İKİZCE", 30 },
                    { 268, "KABADÜZ", 30 },
                    { 269, "KABATAŞ", 30 },
                    { 270, "KORGAN", 30 },
                    { 271, "KUMRU", 30 },
                    { 272, "MESUDİYE", 30 },
                    { 273, "MERKEZ", 30 },
                    { 274, "PERŞEMBE", 30 },
                    { 275, "ULUBEY", 30 },
                    { 276, "ÜNYE", 30 },
                    { 277, "ALTUNHİSAR", 31 },
                    { 278, "BOR", 31 },
                    { 279, "ÇAMARDI", 31 },
                    { 280, "ÇİFTLİK", 31 },
                    { 281, "MERKEZ", 31 },
                    { 282, "ULUKIŞLA", 31 },
                    { 283, "ACIGÖL", 32 },
                    { 284, "AVANOS", 32 },
                    { 285, "DERİNKUYU", 32 },
                    { 286, "GÜLŞEHİR", 32 },
                    { 287, "HACIBEKTAŞ", 32 },
                    { 288, "KOZAKLI", 32 },
                    { 289, "MERKEZ", 32 },
                    { 290, "ÜRGÜP", 32 },
                    { 291, "BULANIK", 33 },
                    { 292, "HASKÖY", 33 },
                    { 293, "KORKUT", 33 },
                    { 294, "MALAZGİRT", 33 },
                    { 295, "MERKEZ", 33 },
                    { 296, "VARTO", 33 },
                    { 297, "BODRUM", 34 },
                    { 298, "DALAMAN", 34 },
                    { 299, "DATÇA", 34 },
                    { 300, "FETHİYE", 34 },
                    { 301, "KAVAKLIDERE", 34 },
                    { 302, "KÖYCEĞİZ", 34 },
                    { 303, "MARMARİS", 34 },
                    { 304, "MİLAS", 34 },
                    { 305, "MERKEZ", 34 },
                    { 306, "ORTACA", 34 },
                    { 307, "ULA", 34 },
                    { 308, "YATAĞAN", 34 },
                    { 309, "DARGEÇİT", 35 },
                    { 310, "DERİK", 35 },
                    { 311, "KIZILTEPE", 35 },
                    { 312, "MERKEZ", 35 },
                    { 313, "MAZIDAĞI", 35 },
                    { 314, "MİDYAT", 35 },
                    { 315, "NUSAYBİN", 35 },
                    { 316, "ÖMERLİ", 35 },
                    { 317, "SAVUR", 35 },
                    { 318, "YEŞİLLİ", 35 },
                    { 319, "AFŞİN", 36 },
                    { 320, "ANDIRIN", 36 },
                    { 322, "EKİNÖZÜ", 36 },
                    { 323, "ELBİSTAN", 36 },
                    { 324, "GÖKSUN", 36 },
                    { 325, "MERKEZ", 36 },
                    { 326, "NURHAK", 36 },
                    { 327, "PAZARCIK", 36 },
                    { 328, "TÜRKOĞLU", 36 },
                    { 329, "AHMETLİ", 37 },
                    { 330, "AKHİSAR", 37 },
                    { 331, "ALAŞEHİR", 37 },
                    { 332, "DEMİRCİ", 37 },
                    { 333, "GÖLMARMARA", 37 },
                    { 334, "GÖRDES", 37 },
                    { 335, "KIRKAĞAÇ", 37 },
                    { 336, "KÖPRÜBAŞI", 37 },
                    { 337, "KULA", 37 },
                    { 338, "MERKEZ", 37 },
                    { 339, "SALİHLİ", 37 },
                    { 340, "SARIGÖL", 37 },
                    { 341, "SARUHANLI", 37 },
                    { 342, "SELENDİ", 37 },
                    { 343, "SOMA", 37 },
                    { 344, "TURGUTLU", 37 },
                    { 345, "AKÇADAĞ", 38 },
                    { 347, "ARGUVAN", 38 },
                    { 348, "BATTALGAZİ", 38 },
                    { 349, "DARENDE", 38 },
                    { 350, "DOĞANŞEHİR", 38 },
                    { 351, "DOĞANYOL", 38 },
                    { 352, "HEKİMHAN", 38 },
                    { 353, "KALE", 38 },
                    { 354, "KULUNCAK", 38 },
                    { 355, "MERKEZ", 38 },
                    { 356, "PÜTÜRGE", 38 },
                    { 357, "YAZIHAN", 38 },
                    { 358, "YEŞİLYURT", 38 },
                    { 359, "ALTINTAŞ", 39 },
                    { 360, "ASLANAPA", 39 },
                    { 361, "ÇAVDARHİSAR", 39 },
                    { 362, "DOMANİÇ", 39 },
                    { 363, "DUMLUPINAR", 39 },
                    { 364, "EMET", 39 },
                    { 365, "GEDİZ", 39 },
                    { 366, "HİSARCIK", 39 },
                    { 367, "MERKEZ", 39 },
                    { 368, "PAZARLAR", 39 },
                    { 369, "SİMAV", 39 },
                    { 370, "ŞAPHANE", 39 },
                    { 371, "TAVŞANLI", 39 },
                    { 372, "AHIRLI", 40 },
                    { 373, "AKÖREN", 40 },
                    { 374, "AKŞEHİR", 40 },
                    { 375, "ALTINEKİN", 40 },
                    { 376, "BEYŞEHİR", 40 },
                    { 377, "BOZKIR", 40 },
                    { 378, "CİHANBEYLİ", 40 },
                    { 379, "ÇELTİK", 40 },
                    { 380, "ÇUMRA", 40 },
                    { 381, "DERBENT", 40 },
                    { 382, "DEREBUCAK", 40 },
                    { 383, "DOĞANHİSAR", 40 },
                    { 384, "EMİRGAZİ", 40 },
                    { 385, "EREĞLİ", 40 },
                    { 386, "GÜNEYSINIR", 40 },
                    { 387, "HADİM", 40 },
                    { 388, "HALKAPINAR", 40 },
                    { 389, "HÜYÜK", 40 },
                    { 390, "ILGIN", 40 },
                    { 391, "KADINHANI", 40 },
                    { 392, "KARAPINAR", 40 },
                    { 393, "KARATAY", 40 },
                    { 394, "KULU", 40 },
                    { 395, "MERAM", 40 },
                    { 396, "SARAYÖNÜ", 40 },
                    { 397, "SELÇUKLU", 40 },
                    { 398, "SEYDİŞEHİR", 40 },
                    { 399, "TAŞKENT", 40 },
                    { 400, "TUZLUKÇU", 40 },
                    { 401, "YALIHÜYÜK", 40 },
                    { 402, "YUNAK", 40 },
                    { 403, "BAŞİSKELE", 41 },
                    { 404, "ÇAYIROVA", 41 },
                    { 405, "DARICA", 41 },
                    { 406, "DERİNCE", 41 },
                    { 407, "DİLOVASI", 41 },
                    { 408, "GEBZE", 41 },
                    { 409, "GÖLCÜK", 41 },
                    { 410, "İZMİT", 41 },
                    { 411, "KANDIRA", 41 },
                    { 412, "KARAMÜRSEL", 41 },
                    { 413, "KARTEPE", 41 },
                    { 414, "KÖRFEZ", 41 },
                    { 415, "AKÇAKENT", 42 },
                    { 416, "AKPINAR", 42 },
                    { 417, "BOZTEPE", 42 },
                    { 418, "ÇİÇEKDAĞI", 42 },
                    { 419, "KAMAN", 42 },
                    { 420, "MERKEZ", 42 },
                    { 421, "MUCUR", 42 },
                    { 422, "BABAESKİ", 43 },
                    { 423, "DEMİRKÖY", 43 },
                    { 424, "MERKEZ", 43 },
                    { 425, "KOFÇAZ", 43 },
                    { 426, "LÜLEBURGAZ", 43 },
                    { 427, "PEHLİVANKÖY", 43 },
                    { 428, "PINARHİSAR", 43 },
                    { 429, "VİZE", 43 },
                    { 430, "AKKIŞLA", 44 },
                    { 431, "BÜNYAN", 44 },
                    { 432, "DEVELİ", 44 },
                    { 433, "FELAHİYE", 44 },
                    { 434, "HACILAR", 44 },
                    { 435, "İNCESU", 44 },
                    { 436, "KOCASİNAN", 44 },
                    { 437, "MELİKGAZİ", 44 },
                    { 438, "ÖZVATAN", 44 },
                    { 439, "PINARBAŞI", 44 },
                    { 440, "SARIOĞLAN", 44 },
                    { 441, "SARIZ", 44 },
                    { 442, "TALAS", 44 },
                    { 443, "TOMARZA", 44 },
                    { 444, "YAHYALI", 44 },
                    { 445, "YEŞİLHİSAR", 44 },
                    { 446, "ABANA", 45 },
                    { 447, "AĞLI", 45 },
                    { 448, "ARAÇ", 45 },
                    { 449, "AZDAVAY", 45 },
                    { 450, "BOZKURT", 45 },
                    { 451, "CİDE", 45 },
                    { 452, "ÇATALZEYTİN", 45 },
                    { 453, "DADAY", 45 },
                    { 454, "DEVREKANİ", 45 },
                    { 455, "DOĞANYURT", 45 },
                    { 456, "HANÖNÜ", 45 },
                    { 457, "İHSANGAZİ", 45 },
                    { 458, "İNEBOLU", 45 },
                    { 459, "MERKEZ", 45 },
                    { 460, "KÜRE", 45 },
                    { 461, "PINARBAŞI", 45 },
                    { 462, "SEYDİLER", 45 },
                    { 463, "ŞENPAZAR", 45 },
                    { 464, "TAŞKÖPRÜ", 45 },
                    { 465, "TOSYA", 45 },
                    { 466, "AKYAKA", 46 },
                    { 467, "ARPAÇAY", 46 },
                    { 468, "DİGOR", 46 },
                    { 469, "KAĞIZMAN", 46 },
                    { 470, "MERKEZ", 46 },
                    { 471, "SARIKAMIŞ", 46 },
                    { 472, "SELİM", 46 },
                    { 473, "SUSUZ", 46 },
                    { 474, "ALİAĞA", 47 },
                    { 475, "BALÇOVA", 47 },
                    { 476, "BAYINDIR", 47 },
                    { 477, "BAYRAKLI", 47 },
                    { 478, "BERGAMA", 47 },
                    { 479, "BEYDAĞ", 47 },
                    { 480, "BORNOVA", 47 },
                    { 481, "BUCA", 47 },
                    { 482, "ÇEŞME", 47 },
                    { 483, "ÇİĞLİ", 47 },
                    { 484, "DİKİLİ", 47 },
                    { 485, "FOÇA", 47 },
                    { 486, "GAZİEMİR", 47 },
                    { 487, "GÜZELBAHÇE", 47 },
                    { 488, "KARABAĞLAR", 47 },
                    { 489, "KARABURUN", 47 },
                    { 490, "KARŞIYAKA", 47 },
                    { 491, "KEMALPAŞA", 47 },
                    { 492, "KINIK", 47 },
                    { 493, "KİRAZ", 47 },
                    { 494, "KONAK", 47 },
                    { 495, "MENDERES", 47 },
                    { 496, "MENEMEN", 47 },
                    { 497, "NARLIDERE", 47 },
                    { 498, "ÖDEMİŞ", 47 },
                    { 499, "SEFERİHİSAR", 47 },
                    { 500, "SELÇUK", 47 },
                    { 501, "TİRE", 47 },
                    { 502, "TORBALI", 47 },
                    { 503, "URLA", 47 },
                    { 504, "ARNAVUTKÖY", 48 },
                    { 505, "AVCILAR", 48 },
                    { 506, "BAĞCILAR", 48 },
                    { 507, "BAHÇELİEVLER", 48 },
                    { 508, "BAKIRKÖY", 48 },
                    { 509, "BAŞAKŞEHİR", 48 },
                    { 510, "BAYRAMPAŞA", 48 },
                    { 511, "BEŞİKTAŞ", 48 },
                    { 512, "BEYLİKDÜZÜ", 48 },
                    { 513, "BEYOĞLU", 48 },
                    { 514, "BÜYÜKÇEKMECE", 48 },
                    { 515, "ÇATALCA", 48 },
                    { 516, "ESENLER", 48 },
                    { 517, "ESENYURT", 48 },
                    { 518, "EYÜPSULTAN", 48 },
                    { 519, "FATİH", 48 },
                    { 520, "GAZİOSMANPAŞA", 48 },
                    { 521, "GÜNGÖREN", 48 },
                    { 522, "KAĞITHANE", 48 },
                    { 523, "KÜÇÜKÇEKMECE", 48 },
                    { 524, "SARIYER", 48 },
                    { 525, "SİLİVRİ", 48 },
                    { 526, "SULTANGAZİ", 48 },
                    { 527, "ZEYTİNBURNU", 48 },
                    { 528, "AKDENİZ", 49 },
                    { 529, "ANAMUR", 49 },
                    { 530, "AYDINCIK", 49 },
                    { 531, "BOZYAZI", 49 },
                    { 532, "ÇAMLIYAYLA", 49 },
                    { 533, "ERDEMLİ", 49 },
                    { 534, "GÜLNAR", 49 },
                    { 535, "MEZİTLİ", 49 },
                    { 536, "MUT", 49 },
                    { 537, "SİLİFKE", 49 },
                    { 538, "TARSUS", 49 },
                    { 539, "TOROSLAR", 49 },
                    { 540, "YENİŞEHİR", 49 },
                    { 541, "AKSU", 50 },
                    { 542, "ATABEY", 50 },
                    { 543, "EĞİRDİR", 50 },
                    { 544, "GELENDOST", 50 },
                    { 545, "GÖNEN", 50 },
                    { 546, "MERKEZ", 50 },
                    { 547, "KEÇİBORLU", 50 },
                    { 548, "SENİRKENT", 50 },
                    { 549, "SÜTÇÜLER", 50 },
                    { 550, "ŞARKİKARAAĞAÇ", 50 },
                    { 551, "ULUBORLU", 50 },
                    { 552, "YALVAÇ", 50 },
                    { 553, "YENİŞARBADEMLİ", 50 },
                    { 554, "ALTINÖZÜ", 51 },
                    { 555, "ANTAKYA", 51 },
                    { 556, "BELEN", 51 },
                    { 557, "DÖRTYOL", 51 },
                    { 558, "ERZİN", 51 },
                    { 559, "HASSA", 51 },
                    { 560, "İSKENDERUN", 51 },
                    { 561, "KIRIKHAN", 51 },
                    { 562, "KUMLU", 51 },
                    { 563, "REYHANLI", 51 },
                    { 564, "SAMANDAĞ", 51 },
                    { 565, "YAYLADAĞI", 51 },
                    { 566, "ÇUKURCA", 52 },
                    { 567, "MERKEZ", 52 },
                    { 568, "ŞEMDİNLİ", 52 },
                    { 569, "YÜKSEKOVA", 52 },
                    { 570, "MERKEZ", 53 },
                    { 571, "KELKİT", 53 },
                    { 572, "KÖSE", 53 },
                    { 573, "KÜRTÜN", 53 },
                    { 574, "ŞİRAN", 53 },
                    { 575, "TORUL", 53 },
                    { 576, "ALUCRA", 54 },
                    { 577, "BULANCAK", 54 },
                    { 578, "ÇAMOLUK", 54 },
                    { 579, "ÇANAKÇI", 54 },
                    { 580, "DERELİ", 54 },
                    { 581, "DOĞANKENT", 54 },
                    { 582, "ESPİYE", 54 },
                    { 583, "EYNESİL", 54 },
                    { 584, "MERKEZ", 54 },
                    { 585, "GÖRELE", 54 },
                    { 586, "GÜCE", 54 },
                    { 587, "KEŞAP", 54 },
                    { 588, "PİRAZİZ", 54 },
                    { 589, "ŞEBİNKARAHİSAR", 54 },
                    { 590, "TİREBOLU", 54 },
                    { 591, "YAĞLIDERE", 54 },
                    { 592, "ARABAN", 55 },
                    { 593, "İSLAHİYE", 55 },
                    { 594, "KARKAMIŞ", 55 },
                    { 595, "NİZİP", 55 },
                    { 596, "NURDAĞI", 55 },
                    { 597, "OĞUZELİ", 55 },
                    { 598, "ŞAHİNBEY", 55 },
                    { 599, "ŞEHİTKAMİL", 55 },
                    { 600, "YAVUZELİ", 55 },
                    { 601, "ALPU", 56 },
                    { 602, "BEYLİKOVA", 56 },
                    { 603, "ÇİFTELER", 56 },
                    { 604, "GÜNYÜZÜ", 56 },
                    { 605, "HAN", 56 },
                    { 606, "İNÖNÜ", 56 },
                    { 607, "MAHMUDİYE", 56 },
                    { 608, "MİHALGAZİ", 56 },
                    { 609, "MİHALIÇÇIK", 56 },
                    { 610, "ODUNPAZARI", 56 },
                    { 611, "SARICAKAYA", 56 },
                    { 612, "SEYİTGAZİ", 56 },
                    { 613, "SİVRİHİSAR", 56 },
                    { 614, "TEPEBAŞI", 56 },
                    { 615, "AŞKALE", 57 },
                    { 616, "AZİZİYE", 57 },
                    { 617, "ÇAT", 57 },
                    { 618, "HINIS", 57 },
                    { 619, "HORASAN", 57 },
                    { 620, "İSPİR", 57 },
                    { 621, "KARAÇOBAN", 57 },
                    { 622, "KARAYAZI", 57 },
                    { 623, "KÖPRÜKÖY", 57 },
                    { 624, "NARMAN", 57 },
                    { 625, "OLTU", 57 },
                    { 626, "OLUR", 57 },
                    { 627, "PALANDÖKEN", 57 },
                    { 628, "PASİNLER", 57 },
                    { 629, "PAZARYOLU", 57 },
                    { 630, "ŞENKAYA", 57 },
                    { 631, "TEKMAN", 57 },
                    { 632, "TORTUM", 57 },
                    { 633, "UZUNDERE", 57 },
                    { 634, "YAKUTİYE", 57 },
                    { 635, "ÇAYIRLI", 58 },
                    { 636, "MERKEZ", 58 },
                    { 638, "KEMAH", 58 },
                    { 639, "KEMALİYE", 58 },
                    { 640, "OTLUKBELİ", 58 },
                    { 641, "REFAHİYE", 58 },
                    { 642, "TERCAN", 58 },
                    { 643, "ÜZÜMLÜ", 58 },
                    { 644, "AĞIN", 59 },
                    { 645, "ALACAKAYA", 59 },
                    { 646, "ARICAK", 59 },
                    { 647, "BASKİL", 59 },
                    { 648, "MERKEZ", 59 },
                    { 649, "KARAKOÇAN", 59 },
                    { 650, "KEBAN", 59 },
                    { 651, "KOVANCILAR", 59 },
                    { 652, "MADEN", 59 },
                    { 653, "PALU", 59 },
                    { 654, "SİVRİCE", 59 },
                    { 655, "MERKEZ", 60 },
                    { 656, "ENEZ", 60 },
                    { 657, "HAVSA", 60 },
                    { 658, "İPSALA", 60 },
                    { 659, "KEŞAN", 60 },
                    { 660, "LALAPAŞA", 60 },
                    { 661, "MERİÇ", 60 },
                    { 662, "SÜLOĞLU", 60 },
                    { 663, "UZUNKÖPRÜ", 60 },
                    { 664, "BAĞLAR", 61 },
                    { 665, "BİSMİL", 61 },
                    { 666, "ÇERMİK", 61 },
                    { 667, "ÇINAR", 61 },
                    { 668, "ÇÜNGÜŞ", 61 },
                    { 669, "DİCLE", 61 },
                    { 670, "EĞİL", 61 },
                    { 671, "ERGANİ", 61 },
                    { 672, "HANİ", 61 },
                    { 673, "HAZRO", 61 },
                    { 674, "KAYAPINAR", 61 },
                    { 675, "KOCAKÖY", 61 },
                    { 676, "KULP", 61 },
                    { 677, "LİCE", 61 },
                    { 678, "SİLVAN", 61 },
                    { 679, "SUR", 61 },
                    { 680, "YENİŞEHİR", 61 },
                    { 681, "ACIPAYAM", 62 },
                    { 682, "PAMUKKALE", 62 },
                    { 683, "BABADAĞ", 62 },
                    { 684, "BAKLAN", 62 },
                    { 685, "BEKİLLİ", 62 },
                    { 686, "BEYAĞAÇ", 62 },
                    { 687, "BOZKURT", 62 },
                    { 688, "BULDAN", 62 },
                    { 689, "ÇAL", 62 },
                    { 690, "ÇAMELİ", 62 },
                    { 691, "ÇARDAK", 62 },
                    { 692, "ÇİVRİL", 62 },
                    { 693, "MERKEZ", 62 },
                    { 694, "GÜNEY", 62 },
                    { 695, "HONAZ", 62 },
                    { 696, "KALE", 62 },
                    { 697, "SARAYKÖY", 62 },
                    { 698, "SERİNHİSAR", 62 },
                    { 699, "TAVAS", 62 },
                    { 700, "ALACA", 63 },
                    { 701, "BAYAT", 63 },
                    { 702, "BOĞAZKALE", 63 },
                    { 703, "MERKEZ", 63 },
                    { 704, "DODURGA", 63 },
                    { 705, "İSKİLİP", 63 },
                    { 706, "KARGI", 63 },
                    { 707, "LAÇİN", 63 },
                    { 708, "MECİTÖZÜ", 63 },
                    { 709, "OĞUZLAR", 63 },
                    { 710, "ORTAKÖY", 63 },
                    { 711, "OSMANCIK", 63 },
                    { 712, "SUNGURLU", 63 },
                    { 713, "UĞURLUDAĞ", 63 },
                    { 714, "ATKARACALAR", 64 },
                    { 715, "BAYRAMÖREN", 64 },
                    { 716, "MERKEZ", 64 },
                    { 717, "ÇERKEŞ", 64 },
                    { 718, "ELDİVAN", 64 },
                    { 719, "ILGAZ", 64 },
                    { 720, "KIZILIRMAK", 64 },
                    { 721, "KORGUN", 64 },
                    { 722, "KURŞUNLU", 64 },
                    { 723, "ORTA", 64 },
                    { 724, "ŞABANÖZÜ", 64 },
                    { 725, "YAPRAKLI", 64 },
                    { 726, "AYVACIK", 65 },
                    { 727, "BAYRAMİÇ", 65 },
                    { 728, "BİGA", 65 },
                    { 729, "BOZCAADA", 65 },
                    { 730, "ÇAN", 65 },
                    { 731, "MERKEZ", 65 },
                    { 732, "ECEABAT", 65 },
                    { 733, "EZİNE", 65 },
                    { 734, "GELİBOLU", 65 },
                    { 735, "GÖKÇEADA", 65 },
                    { 736, "LAPSEKİ", 65 },
                    { 737, "YENİCE", 65 },
                    { 738, "BÜYÜKORHAN", 66 },
                    { 739, "GEMLİK", 66 },
                    { 740, "GÜRSU", 66 },
                    { 741, "HARMANCIK", 66 },
                    { 742, "İNEGÖL", 66 },
                    { 743, "İZNİK", 66 },
                    { 744, "KARACABEY", 66 },
                    { 745, "KELES", 66 },
                    { 746, "KESTEL", 66 },
                    { 747, "MUDANYA", 66 },
                    { 748, "MUSTAFAKEMALPAŞA", 66 },
                    { 749, "NİLÜFER", 66 },
                    { 750, "ORHANELİ", 66 },
                    { 751, "ORHANGAZİ", 66 },
                    { 752, "OSMANGAZİ", 66 },
                    { 753, "YENİŞEHİR", 66 },
                    { 754, "YILDIRIM", 66 },
                    { 755, "AĞLASUN", 67 },
                    { 756, "ALTINYAYLA", 67 },
                    { 757, "BUCAK", 67 },
                    { 758, "MERKEZ", 67 },
                    { 759, "ÇAVDIR", 67 },
                    { 760, "ÇELTİKÇİ", 67 },
                    { 761, "GÖLHİSAR", 67 },
                    { 762, "KARAMANLI", 67 },
                    { 763, "KEMER", 67 },
                    { 764, "TEFENNİ", 67 },
                    { 765, "YEŞİLOVA", 67 },
                    { 766, "MERKEZ", 68 },
                    { 767, "DÖRTDİVAN", 68 },
                    { 768, "GEREDE", 68 },
                    { 769, "GÖYNÜK", 68 },
                    { 770, "KIBRISCIK", 68 },
                    { 771, "MENGEN", 68 },
                    { 772, "MUDURNU", 68 },
                    { 773, "SEBEN", 68 },
                    { 774, "YENİÇAĞA", 68 },
                    { 775, "ADİLCEVAZ", 69 },
                    { 776, "AHLAT", 69 },
                    { 777, "MERKEZ", 69 },
                    { 778, "GÜROYMAK", 69 },
                    { 779, "HİZAN", 69 },
                    { 780, "MUTKİ", 69 },
                    { 781, "TATVAN", 69 },
                    { 782, "ADAKLI", 70 },
                    { 783, "MERKEZ", 70 },
                    { 784, "GENÇ", 70 },
                    { 785, "KARLIOVA", 70 },
                    { 786, "KİĞI", 70 },
                    { 787, "SOLHAN", 70 },
                    { 788, "YAYLADERE", 70 },
                    { 789, "YEDİSU", 70 },
                    { 790, "MERKEZ", 71 },
                    { 791, "BOZÜYÜK", 71 },
                    { 792, "GÖLPAZARI", 71 },
                    { 793, "İNHİSAR", 71 },
                    { 794, "OSMANELİ", 71 },
                    { 795, "PAZARYERİ", 71 },
                    { 796, "SÖĞÜT", 71 },
                    { 797, "YENİPAZAR", 71 },
                    { 798, "AYVALIK", 72 },
                    { 799, "MERKEZ", 72 },
                    { 800, "BALYA", 72 },
                    { 801, "BANDIRMA", 72 },
                    { 802, "BİGADİÇ", 72 },
                    { 803, "BURHANİYE", 72 },
                    { 804, "DURSUNBEY", 72 },
                    { 805, "EDREMİT", 72 },
                    { 806, "ERDEK", 72 },
                    { 807, "GÖMEÇ", 72 },
                    { 808, "GÖNEN", 72 },
                    { 809, "HAVRAN", 72 },
                    { 810, "İVRİNDİ", 72 },
                    { 811, "KEPSUT", 72 },
                    { 812, "MANYAS", 72 },
                    { 813, "MARMARA", 72 },
                    { 814, "SAVAŞTEPE", 72 },
                    { 815, "SINDIRGI", 72 },
                    { 816, "SUSURLUK", 72 },
                    { 817, "MERKEZ", 73 },
                    { 818, "BOZDOĞAN", 73 },
                    { 819, "BUHARKENT", 73 },
                    { 820, "ÇİNE", 73 },
                    { 821, "DİDİM", 73 },
                    { 822, "GERMENCİK", 73 },
                    { 823, "İNCİRLİOVA", 73 },
                    { 824, "KARACASU", 73 },
                    { 825, "KARPUZLU", 73 },
                    { 826, "KOÇARLI", 73 },
                    { 827, "KÖŞK", 73 },
                    { 828, "KUŞADASI", 73 },
                    { 829, "KUYUCAK", 73 },
                    { 830, "NAZİLLİ", 73 },
                    { 831, "SÖKE", 73 },
                    { 832, "SULTANHİSAR", 73 },
                    { 833, "YENİPAZAR", 73 },
                    { 834, "ARDANUÇ", 74 },
                    { 835, "ARHAVİ", 74 },
                    { 836, "MERKEZ", 74 },
                    { 837, "BORÇKA", 74 },
                    { 838, "HOPA", 74 },
                    { 839, "MURGUL", 74 },
                    { 840, "ŞAVŞAT", 74 },
                    { 841, "YUSUFELİ", 74 },
                    { 842, "AKSEKİ", 75 },
                    { 843, "AKSU", 75 },
                    { 844, "ALANYA", 75 },
                    { 845, "DEMRE", 75 },
                    { 846, "DÖŞEMEALTI", 75 },
                    { 847, "ELMALI", 75 },
                    { 848, "FİNİKE", 75 },
                    { 849, "GAZİPAŞA", 75 },
                    { 850, "GÜNDOĞMUŞ", 75 },
                    { 851, "İBRADI", 75 },
                    { 852, "KAŞ", 75 },
                    { 853, "KEMER", 75 },
                    { 854, "KEPEZ", 75 },
                    { 855, "KONYAALTI", 75 },
                    { 856, "KORKUTELİ", 75 },
                    { 857, "KUMLUCA", 75 },
                    { 858, "MANAVGAT", 75 },
                    { 859, "MURATPAŞA", 75 },
                    { 860, "SERİK", 75 },
                    { 861, "AKYURT", 76 },
                    { 862, "ALTINDAĞ", 76 },
                    { 863, "AYAŞ", 76 },
                    { 864, "BALA", 76 },
                    { 865, "BEYPAZARI", 76 },
                    { 866, "ÇAMLIDERE", 76 },
                    { 867, "ÇANKAYA", 76 },
                    { 868, "ÇUBUK", 76 },
                    { 869, "ELMADAĞ", 76 },
                    { 870, "ETİMESGUT", 76 },
                    { 871, "EVREN", 76 },
                    { 872, "GÖLBAŞI", 76 },
                    { 873, "GÜDÜL", 76 },
                    { 874, "HAYMANA", 76 },
                    { 875, "KALECİK", 76 },
                    { 876, "KAHRAMANKAZAN", 76 },
                    { 877, "KEÇİÖREN", 76 },
                    { 878, "KIZILCAHAMAM", 76 },
                    { 879, "MAMAK", 76 },
                    { 880, "NALLIHAN", 76 },
                    { 881, "POLATLI", 76 },
                    { 882, "PURSAKLAR", 76 },
                    { 883, "SİNCAN", 76 },
                    { 884, "ŞEREFLİKOÇHİSAR", 76 },
                    { 885, "YENİMAHALLE", 76 },
                    { 886, "MERKEZ", 77 },
                    { 887, "GÖYNÜCEK", 77 },
                    { 888, "GÜMÜŞHACIKÖY", 77 },
                    { 889, "HAMAMÖZÜ", 77 },
                    { 890, "MERZİFON", 77 },
                    { 891, "SULUOVA", 77 },
                    { 892, "TAŞOVA", 77 },
                    { 893, "MERKEZ", 78 },
                    { 894, "DİYADİN", 78 },
                    { 895, "DOĞUBAYAZIT", 78 },
                    { 896, "ELEŞKİRT", 78 },
                    { 897, "HAMUR", 78 },
                    { 898, "PATNOS", 78 },
                    { 899, "TAŞLIÇAY", 78 },
                    { 900, "TUTAK", 78 },
                    { 901, "MERKEZ", 79 },
                    { 902, "BAŞMAKÇI", 79 },
                    { 903, "BAYAT", 79 },
                    { 904, "BOLVADİN", 79 },
                    { 905, "ÇAY", 79 },
                    { 906, "ÇOBANLAR", 79 },
                    { 907, "DAZKIRI", 79 },
                    { 908, "DİNAR", 79 },
                    { 909, "EMİRDAĞ", 79 },
                    { 910, "EVCİLER", 79 },
                    { 911, "HOCALAR", 79 },
                    { 912, "İHSANİYE", 79 },
                    { 913, "İSCEHİSAR", 79 },
                    { 914, "KIZILÖREN", 79 },
                    { 915, "SANDIKLI", 79 },
                    { 917, "SULTANDAĞI", 79 },
                    { 918, "ŞUHUT", 79 },
                    { 919, "MERKEZ", 80 },
                    { 920, "BESNİ", 80 },
                    { 921, "ÇELİKHAN", 80 },
                    { 922, "GERGER", 80 },
                    { 923, "GÖLBAŞI", 80 },
                    { 924, "KAHTA", 80 },
                    { 925, "SAMSAT", 80 },
                    { 926, "SİNCİK", 80 },
                    { 927, "TUT", 80 },
                    { 928, "ALADAĞ", 81 },
                    { 929, "CEYHAN", 81 },
                    { 930, "ÇUKUROVA", 81 },
                    { 931, "FEKE", 81 },
                    { 934, "GÜZELYURT", 81 },
                    { 935, "İMAMOĞLU", 81 },
                    { 936, "KARAİSALI", 81 },
                    { 937, "KARATAŞ", 81 },
                    { 938, "KOZAN", 81 },
                    { 939, "POZANTI", 81 },
                    { 940, "SAİMBEYLİ", 81 },
                    { 941, "SARIÇAM", 81 },
                    { 942, "SEYHAN", 81 },
                    { 943, "TUFANBEYLİ", 81 },
                    { 944, "YUMURTALIK", 81 },
                    { 945, "YÜREĞİR", 81 },
                    { 946, "ADALAR", 48 },
                    { 947, "ATAŞEHİR", 48 },
                    { 948, "BEYKOZ", 48 },
                    { 949, "ÇEKMEKÖY", 48 },
                    { 950, "KADIKÖY", 48 },
                    { 951, "KARTAL", 48 },
                    { 952, "MALTEPE", 48 },
                    { 953, "PENDİK", 48 },
                    { 954, "SANCAKTEPE", 48 },
                    { 955, "SULTANBEYLİ", 48 },
                    { 956, "ŞİLE", 48 },
                    { 957, "ŞİŞLİ", 48 },
                    { 958, "TUZLA", 48 },
                    { 959, "ÜMRANİYE", 48 },
                    { 960, "ÜSKÜDAR", 48 },
                    { 961, "MERKEZ", 48 },
                    { 962, "MERKEZ", 27 },
                    { 963, "MERKEZ", 28 },
                    { 964, "MERKEZ", 40 },
                    { 965, "MERKEZ", 41 },
                    { 966, "MERKEZ", 44 },
                    { 967, "MERKEZ", 47 },
                    { 968, "MERKEZ", 49 },
                    { 969, "MERKEZ", 51 },
                    { 970, "MERKEZ", 55 },
                    { 971, "MERKEZ", 56 },
                    { 972, "MERKEZ", 57 },
                    { 973, "MERKEZ", 61 },
                    { 974, "MERKEZ", 66 },
                    { 975, "MERKEZ", 75 },
                    { 976, "MERKEZ", 76 },
                    { 977, "MERKEZ", 81 },
                    { 978, "ŞEHZADELER", 37 },
                    { 979, "EFELER", 73 },
                    { 980, "YUNUSEMRE", 37 },
                    { 981, "HALİLİYE", 19 },
                    { 982, "DEFNE", 51 },
                    { 983, "KARAKÖPRÜ", 19 },
                    { 984, "ALTIEYLÜL", 72 },
                    { 985, "KARESİ", 72 },
                    { 986, "ALTINORDU", 30 },
                    { 987, "SÜLEYMANPAŞA", 23 },
                    { 988, "EYYÜBİYE", 19 },
                    { 989, "KİLİMLİ", 15 },
                    { 990, "KAPAKLI", 23 },
                    { 992, "PAYAS", 51 },
                    { 993, "ERGENE", 23 },
                    { 994, "SİNANPAŞA", 79 },
                    { 995, "MERKEZEFENDİ", 62 },
                    { 996, "İLİÇ", 58 },
                    { 997, "ARSUZ", 51 },
                    { 998, "ÇAĞLAYANCERİT", 36 },
                    { 999, "DULKADİROĞLU", 36 },
                    { 1000, "ONİKİŞUBAT", 36 },
                    { 1001, "ARAPGİR", 38 },
                    { 1002, "ARTUKLU", 35 },
                    { 1003, "MENTEŞE", 34 },
                    { 1004, "SEYDİKEMER", 34 },
                    { 1005, "19-May", 27 },
                    { 1006, "TİLLO", 26 },
                    { 1007, "ORTAHİSAR", 21 },
                    { 1008, "İPEKYOLU", 17 },
                    { 1009, "TUŞBA", 17 },
                    { 1010, "KOZLU", 15 }
                });

            migrationBuilder.InsertData(
                table: "RolePermissions",
                columns: new[] { "PermissionId", "RoleId" },
                values: new object[,]
                {
                    { 1, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 2, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 3, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 4, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 5, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 6, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 7, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 8, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 9, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 10, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 11, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 12, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") },
                    { 13, new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5") }
                });

            migrationBuilder.InsertData(
                table: "UserRoles",
                columns: new[] { "RoleId", "UserId" },
                values: new object[] { new Guid("3382e069-ec63-48c6-bf92-c76987d43fc5"), new Guid("b8c4f733-8811-47dc-83f1-6a88d3edf782") });

            migrationBuilder.CreateIndex(
                name: "IX_Districts_ProvinceId",
                table: "Districts",
                column: "ProvinceId");

            migrationBuilder.CreateIndex(
                name: "IX_RoleClaims_RoleId",
                table: "RoleClaims",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "IX_RolePermissions_PermissionId",
                table: "RolePermissions",
                column: "PermissionId");

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "Roles",
                column: "NormalizedName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_UserClaims_UserId",
                table: "UserClaims",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_UserLogins_UserId",
                table: "UserLogins",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_UserRefreshTokens_UserId",
                table: "UserRefreshTokens",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_UserRoles_RoleId",
                table: "UserRoles",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "EmailIndex",
                table: "Users",
                column: "NormalizedEmail");

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "Users",
                column: "NormalizedUserName",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Districts");

            migrationBuilder.DropTable(
                name: "RoleClaims");

            migrationBuilder.DropTable(
                name: "RolePermissions");

            migrationBuilder.DropTable(
                name: "UserClaims");

            migrationBuilder.DropTable(
                name: "UserLogins");

            migrationBuilder.DropTable(
                name: "UserRefreshTokens");

            migrationBuilder.DropTable(
                name: "UserRoles");

            migrationBuilder.DropTable(
                name: "UserTokens");

            migrationBuilder.DropTable(
                name: "Provinces");

            migrationBuilder.DropTable(
                name: "Permissions");

            migrationBuilder.DropTable(
                name: "Roles");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
